services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 10s
      retries: 5
    restart: always

  anime_pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: anime_data_pipeline_container
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    # Lệnh này giữ cho container sống để bạn có thể nhảy vào chạy code
    command: tail -f /dev/null 

volumes:
  postgres_data: